version: '3'

services:
  postgres-db-qpt:
    container_name: postgres-db-qpt
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - postgres-qpt
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASSWORD=airpass
      - POSTGRES_USER=airuser
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - c:\Users\lgaluzin\docker_shared\demo-big:/tmp
#      - c:\Users\lgaluzin\Downloads\demo-big:/docker-entrypoint-initdb.d

networks:
  postgres-qpt:
