version: '3'

services:
  postgres-db-qpt:
    container_name: postgres-db-qpt
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - postgres-qpt
    ports:
      - 25432:5432
    environment:
#      - POSTGRES_PASSWORD=airpass
#      - POSTGRES_USER=airuser
#      - POSTGRES_DB=demo
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ~/Downloadsc:/docker-entrypoint-initdb.d/psql-dump.sql

networks:
  postgres-qpt:
